### ISSUE TITLE
Error while getting memo for sent transactions

### ISSUE THREAD

**Issue by Mandeepbhalothia** [zcash/zcash-android-wallet-sdk#1108]
### Describe the issue
When we try to get the memo of a sent type transaction we get error and that leads to app crash

In SdkSynchronizer the below method is used to get the memo

`override fun getMemos(transactionOverview: TransactionOverview): Flow<String> {
        return storage.getNoteIds(transactionOverview.id).map {
            when (transactionOverview.isSentTransaction) {
                true -> {
                    backend.getSentMemoAsUtf8(it)
                }
                false -> {
                    backend.getReceivedMemoAsUtf8(it)
                }
            }
        }.filterNotNull()
    }`

And following exception is caught in logcat:

`FATAL EXCEPTION: main
                                                                                                    Process: com.nighthawkapps.wallet.android, PID: 21712
                                                                                                    java.lang.RuntimeException: An error occurred retrieving the memo, Query returned no rows
                                                                                                    	at cash.z.ecc.android.sdk.internal.jni.RustBackend.getSentMemoAsUtf8(Native Method)
                                                                                                    	at cash.z.ecc.android.sdk.internal.jni.RustBackend.access$getSentMemoAsUtf8(RustBackend.kt:17)
                                                                                                    	at cash.z.ecc.android.sdk.internal.jni.RustBackend$Companion.getSentMemoAsUtf8(Unknown Source:0)
                                                                                                    	at cash.z.ecc.android.sdk.internal.jni.RustBackend$Companion.access$getSentMemoAsUtf8(RustBackend.kt:384)
                                                                                                    	at cash.z.ecc.android.sdk.internal.jni.RustBackend$getSentMemoAsUtf8$2.invokeSuspend(RustBackend.kt:170)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)
                                                                                                    	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@4789b34, Dispatchers.Main.immediate]`

#### If so, please list the steps to reproduce below:
1. Try to get any Sent transaction that has memo associated with it. It will crash

### Expected behaviour
We should not get the crash and should able to get the memo and required details

**Comment by HonzaR** [comment]
Hi @Mandeepbhalothia. Thank you for reporting this. We handle the expected `RuntimeException` on the caller side - in the Demo app, but handling it on the SDK's side seems like a good improvement. I'll prepare the necessary changes, which will be part of the next SDK release.

**Comment by Mandeepbhalothia** [comment]
Hi @HonzaR Thanks for considering this. I tried to get the memo for sent transactions like below on testnet.

`synchronizer.getMemos(transactionOverview).collectLatest { memo -> }`

While I am trying to get the memo for sent transactions I am getting empty("") string but while I am trying to get on the account where it is sent it is showing proper memo with same method.

Example:- Let's transfer from Account A to B with `memo = "Trying to send some for testing"`. While I try to get the memo in account A it is showing `memo = ""`  and in Account B `memo= "Trying to send some for testing"`.
