### ISSUE TITLE
App crash after Shielding transparent balance

### ISSUE THREAD

**Issue by Mandeepbhalothia** [zcash/zcash-android-wallet-sdk#1110]
### Describe the issue
When we try to shield the transparent balance after crashes immediately after the shielding

#### If so, please list the steps to reproduce below:
1. Check with old account in which few transactions are already there
2. Make some transparent balance available
3. Shield the balance 

### Expected behaviour
It should not crash after shielding

### Actual behavior + errors
`main                           CheckpointTool.loadCheckpointFromAssets(): loading checkpoint from assets: BlockHeight(value=1700000)
2023-07-08 19:26:42.141  6893-6893  Twig                    com...hawkapps.wallet.android.debug  D                              main                           CheckpointTool.loadCheckpointFromAssets(): found 123 sapling tree checkpoints: [1700000.json, 1690000.json, 1687104.json, 1680000.json, 1670000.json, 1660000.json, 1650000.json, 1640000.json, 1630000.json, 1620000.json, 1610000.json, 1600000.json, 1590000.json, 1580000.json, 1570000.json, 1560000.json, 1550000.json, 1540000.json, 1530000.json, 1520000.json, 1510000.json, 1500000.json, 1490000.json, 1480000.json, 1470000.json, 1460000.json, 1450000.json, 1440000.json, 1430000.json, 1420000.json, 1410000.json, 1400000.json, 1390000.json, 1380000.json, 1370000.json, 1360000.json, 1350000.json, 1340000.json, 1330000.json, 1320000.json, 1310000.json, 1300000.json, 1290000.json, 1280000.json, 1270000.json, 1260000.json, 1250000.json, 1240000.json, 1230000.json, 1220000.json, 1210000.json, 1200000.json, 1190000.json, 1180000.json, 1170000.json, 1160000.json, 1150000.json, 1140000.json, 1130000.json, 1120000.json, 1110000.json, 1100000.json, 1090000.json, 1080000.json, 1070000.json, 1060000.json, 1050000.json, 1040000.json, 1030000.json, 1020000.json, 1010000.json, 1000000.json, 990000.json, 980000.json, 970000.json, 960000.json, 950000.json, 940000.json, 930000.json, 920000.json, 910000.json, 900000.json, 890000.json, 880000.json, 870000.json, 860000.json, 850000.json, 840000.json, 830000.json, 820000.json, 810000.json, 800000.json, 790000.json, 780000.json, 770000.json, 760000.json, 750000.json, 740000.json, 730000.json, 720000.json, 710000.json, 700000.json, 690000.json, 680000.json, 670000.json, 660000.json, 650000.json, 640000.json, 630000.json, 620000.json, 610000.json, 600000.json, 590000.json, 580000.json, 570000.json, 560000.json, 550000.json, 540000.json, 530000.json, 520000.json, 510000.json, 500000.json, 419200.json]
2023-07-08 19:26:42.161  6893-6893  Twig                    com...hawkapps.wallet.android.debug  D                              main                           DatabaseCoordinator.fsBlockDbRoot$zcash_android_sdk_1_18_0_beta01_release(): Legacy Cache database files are successfully deleted.
2023-07-08 19:26:42.168  6893-6893  Twig                    com...hawkapps.wallet.android.debug  D                              main                           DatabaseCoordinator.fsBlockDbRoot$zcash_android_sdk_1_18_0_beta01_release(): Legacy Cache database files are successfully deleted.
2023-07-08 19:26:42.177  6893-6944  cash.z.rust.logs        com...hawkapps.wallet.android.debug  I  schemer: Migrating up to target: None    
2023-07-08 19:26:42.187  6893-6944  cash.z.rust.logs        com...hawkapps.wallet.android.debug  I  schemer: Migrating up to target: None    
2023-07-08 19:26:42.194  6893-6893  Twig                    com...hawkapps.wallet.android.debug  D                              main                           DerivedDataDb.new(): 
                                                                                                    java.lang.RuntimeException: Error while initializing blocks table: Table is not empty
                                                                                                    	at cash.z.ecc.android.sdk.internal.jni.RustBackend.initBlocksTable(Native Method)
                                                                                                    	at cash.z.ecc.android.sdk.internal.jni.RustBackend.access$initBlocksTable(RustBackend.kt:17)
                                                                                                    	at cash.z.ecc.android.sdk.internal.jni.RustBackend$Companion.initBlocksTable(Unknown Source:0)
                                                                                                    	at cash.z.ecc.android.sdk.internal.jni.RustBackend$Companion.access$initBlocksTable(RustBackend.kt:384)
                                                                                                    	at cash.z.ecc.android.sdk.internal.jni.RustBackend$initBlocksTable$2.invokeSuspend(RustBackend.kt:101)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
                                                                                                    	at java.lang.Thread.run(Thread.java:923)
2023-07-08 19:26:42.196  6893-6893  Twig                    com...hawkapps.wallet.android.debug  D                              main                           DerivedDataDb.new(): 
                                                                                                    java.lang.RuntimeException: Error while initializing accounts: Table is not empty
                                                                                                    	at cash.z.ecc.android.sdk.internal.jni.RustBackend.initAccountsTableWithKeys(Native Method)
                                                                                                    	at cash.z.ecc.android.sdk.internal.jni.RustBackend.access$initAccountsTableWithKeys(RustBackend.kt:17)
                                                                                                    	at cash.z.ecc.android.sdk.internal.jni.RustBackend$Companion.initAccountsTableWithKeys(Unknown Source:0)
                                                                                                    	at cash.z.ecc.android.sdk.internal.jni.RustBackend$Companion.access$initAccountsTableWithKeys(RustBackend.kt:384)
                                                                                                    	at cash.z.ecc.android.sdk.internal.jni.RustBackend$initAccountsTable$2.invokeSuspend(RustBackend.kt:86)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
                                                                                                    	at java.lang.Thread.run(Thread.java:923)
2023-07-08 19:26:42.197  6893-6928  Twig                    com...hawkapps.wallet.android.debug  D                              DefaultDispatcher-worker-1     NoBackupContextWrapper.getDatabasePath(): Database: zcash_sdk_mainnet_data.sqlite3 in directory: /data/user/0/com.nighthawkapps.wallet.android.debug/no_backup/co.electricoin.zcash
2023-07-08 19:26:42.198  6893-6928  Twig                    com...hawkapps.wallet.android.debug  D                              DefaultDispatcher-worker-1     NoBackupContextWrapper.getDatabasePath(): Database: zcash_sdk_mainnet_data.sqlite3 in directory: /data/user/0/com.nighthawkapps.wallet.android.debug/no_backup/co.electricoin.zcash
2023-07-08 19:26:42.242  6893-6893  Twig                    com...hawkapps.wallet.android.debug  D                              main                           SdkSynchronizer.onReady(): Starting synchronizer…
2023-07-08 19:26:42.248  6893-6893  Twig                    com...hawkapps.wallet.android.debug  D                              main                           CompactBlockProcessor.refreshUtxos$zcash_android_sdk_1_18_0_beta01_release(): Checking for UTXOs above height BlockHeight(value=419200)
2023-07-08 19:26:42.325  6893-6893  AndroidRuntime          com...hawkapps.wallet.android.debug  E  FATAL EXCEPTION: main
                                                                                                    Process: com.nighthawkapps.wallet.android.debug, PID: 6893
                                                                                                    java.lang.IllegalArgumentException: Height 0 is below sapling activation height BlockHeight(value=419200)
                                                                                                    	at cash.z.ecc.android.sdk.model.BlockHeight$Companion.new(BlockHeight.kt:51)
                                                                                                    	at cash.z.ecc.android.sdk.internal.db.derived.AllTransactionView.cursorParser$lambda$1(AllTransactionView.kt:93)
                                                                                                    	at cash.z.ecc.android.sdk.internal.db.derived.AllTransactionView.$r8$lambda$sh8WI0uAr935DnwvrWEILjvyheo(Unknown Source:0)
                                                                                                    	at cash.z.ecc.android.sdk.internal.db.derived.AllTransactionView$$ExternalSyntheticLambda2.newObject(Unknown Source:2)
                                                                                                    	at cash.z.ecc.android.sdk.internal.db.SQLiteDatabaseExtKt$queryAndMap$2.invokeSuspend(SQLiteDatabaseExt.kt:108)
                                                                                                    	at cash.z.ecc.android.sdk.internal.db.SQLiteDatabaseExtKt$queryAndMap$2.invoke(Unknown Source:8)
                                                                                                    	at cash.z.ecc.android.sdk.internal.db.SQLiteDatabaseExtKt$queryAndMap$2.invoke(Unknown Source:4)
                                                                                                    	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
                                                                                                    	at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
                                                                                                    	at kotlinx.coroutines.flow.internal.ChannelFlowOperatorImpl.flowCollect(ChannelFlow.kt:195)
                                                                                                    	at kotlinx.coroutines.flow.internal.ChannelFlowOperator.collectTo$suspendImpl(ChannelFlow.kt:157)
                                                                                                    	at kotlinx.coroutines.flow.internal.ChannelFlowOperator.collectTo(Unknown Source:0)
                                                                                                    	at kotlinx.coroutines.flow.internal.ChannelFlow$collectToFun$1.invokeSuspend(ChannelFlow.kt:60)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                                                                                                    	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
                                                                                                    	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:100)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
                                                                                                    	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@270a78d, Dispatchers.Main.immediate]
2023-07-08 19:26:42.368  6796-6828  MediaScannerConnection  com...hawkapps.wallet.android.debug  D  Scanned /storage/emulated/0/Android/data/com.nighthawkapps.wallet.android.debug/files/log/exception/1688858802|7dc4178e-7ff2-4c1e-8159-0cf70b096f24|java.lang.IllegalArgumentException|true.txt to null
`

**Comment by HonzaR** [comment]
Hi @Mandeepbhalothia, Thank you for reporting this issue! From the log you've attached, I see you're using the SDK version `1.18.0-beta01`. The new version `1.19.0-beta01` fixes this trouble. Please update and let me know if that helped. Thank you!

**Comment by Mandeepbhalothia** [comment]
Hi @HonzaR, Thanks for fixing the issue. Now able to shield the funds. But faced another issue, I am not able to send the shielded amount to another testnet address. 

`TransactionEncoderImpl.createSpend(): Caught exception while creating transaction.
                                                                                                    androidx.compose.runtime.LeftCompositionCancellationException: The coroutine scope left the composition`
                                                                                                    
Any suggestion on this, Should I open a new bug for this?

**Comment by HonzaR** [comment]
Yes, please, open a new issue for this. We need to examine it.
