### ISSUE TITLE
Sync AbortFlowException (sdk-v2.0.0-rc.1 - rc.3) 

### ISSUE THREAD

**Issue by Mandeepbhalothia** [zcash/zcash-android-wallet-sdk#1264]
### Describe the issue
During sync with sdk v2 version getting the issue about AbortFlowException

#### If so, please list the steps to reproduce below:
1. During simple sync on an old wallet 

After few times of retries it start download and sync few last blocks and then continue downloading and syncing.

### Any extra information that might be useful in the debugging process.
CompactBlockDownloader.invokeSuspend(): Blocks in range BlockHeight(value=1723072)..BlockHeight(value=1723171) failed to download with: kotlinx.coroutines.flow.internal.AbortFlowException: Flow was aborted, no more elements needed
2023-09-22 21:08:47.336 29923-29923 Twig                    com.nighthawkapps.wallet.android     W                              main                           CompactBlockProcessor.downloadBatchOfBlocks$zcash_android_sdk_2_0_0_rc_3_release(): Retrying (1/5) in 500s...
                                                                                                    kotlinx.coroutines.flow.internal.AbortFlowException: Flow was aborted, no more elements needed
2023-09-22 21:08:47.337 29923-29923 Twig                    com.nighthawkapps.wallet.android     D                              main                           CompactBlockProcessor.start(): processNewBlocks MUTEX: releasing lock
2023-09-22 21:08:47.338 29923-29923 Twig                    com.nighthawkapps.wallet.android     I                              main                           CompactBlockProcessor.start(): Planned restarting of block synchronization...
2023-09-22 21:08:47.338 29923-29923 Twig                    com.nighthawkapps.wallet.android     D                              main                           CompactBlockProcessor.start(): processNewBlocks MUTEX: acquiring lock...
2023-09-22 21:08:47.339 29923-29923 Twig                    com.nighthawkapps.wallet.android     D                              main                           CompactBlockProcessor.start(): processNewBlocks MUTEX: ...lock acquired!
2023-09-22 21:08:52.632 29923-29923 Twig                    com.nighthawkapps.wallet.android     I                              main                           CompactBlockProcessor.putSaplingSubtreeRoots$zcash_android_sdk_2_0_0_rc_3_release(): Sapling subtree roots put successfully with startIndex: 0 and roots: 1114
2023-09-22 21:08:52.632 29923-29923 Twig                    com.nighthawkapps.wallet.android     I                              main                           CompactBlockProcessor.processNewBlocksInSbSOrder(): Beginning to process new blocks with Spend-before-Sync approach with lower bound: BlockHeight(value=1079900))...
2023-09-22 21:08:52.633 29923-29923 Twig                    com.nighthawkapps.wallet.android     D                              main                           CompactBlockProcessor.fetchLatestBlockHeight$zcash_android_sdk_2_0_0_rc_3_release(): Fetching latest block height...
2023-09-22 21:09:02.640 29923-29923 LightWalletClient       com.nighthawkapps.wallet.android     W  Networking error: DEADLINE_EXCEEDED: deadline exceeded after 9.996491770s. [closed=[], open=[[remote_addr=mainnet.lightwalletd.com/140.238.134.157:9067]]]
2023-09-22 21:09:02.641 29923-29923 Twig                    com.nighthawkapps.wallet.android     E                              main                           CompactBlockProcessor.fetchLatestBlockHeight$zcash_android_sdk_2_0_0_rc_3_release(): Fetching latest block height failed with: java.lang.Throwable: Communication failure with details: 4: deadline exceeded after 9.996491770s. [closed=[], open=[[remote_addr=mainnet.lightwalletd.com/140.238.134.157:9067]]]
2023-09-22 21:09:02.645 29923-29923 Twig                    com.nighthawkapps.wallet.android     W                              main                           CompactBlockProcessor.fetchLatestBlockHeight$zcash_android_sdk_2_0_0_rc_3_release(): Retrying (1/3) in 500s...
                                                                                                    cash.z.ecc.android.sdk.exception.LightWalletException$GetLatestBlockHeightException: Failed to fetch latest block height with code: 4 due to: deadline exceeded after 9.996491770s. [closed=[], open=[[remote_addr=mainnet.lightwalletd.com/140.238.134.157:9067]]]
                                                                                                    	at cash.z.ecc.android.sdk.block.processor.CompactBlockProcessor$Companion.fetchLatestBlockHeight$zcash_android_sdk_2_0_0_rc_3_release(CompactBlockProcessor.kt:1081)
                                                                                                    	at cash.z.ecc.android.sdk.block.processor.CompactBlockProcessor$Companion$fetchLatestBlockHeight$1.invokeSuspend(Unknown Source:15)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:32)
                                                                                                    	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:938)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:226)
                                                                                                    	at android.os.Looper.loop(Looper.java:313)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8663)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
                                                                                                    Caused by: java.lang.Throwable: Communication failure with details: 4: deadline exceeded after 9.996491770s. [closed=[], open=[[remote_addr=mainnet.lightwalletd.com/140.238.134.157:9067]]]
                                                                                                    	at co.electriccoin.lightwallet.client.model.Response$Failure.toThrowable(Response.kt:18)
                                                                                                    	at cash.z.ecc.android.sdk.block.processor.CompactBlockProcessor$Companion.fetchLatestBlockHeight$zcash_android_sdk_2_0_0_rc_3_release(CompactBlockProcessor.kt:1084)
                                                                                                    	at cash.z.ecc.android.sdk.block.processor.CompactBlockProcessor$Companion$fetchLatestBlockHeight$1.invokeSuspend(Unknown Source:15) 
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) 
                                                                                                    	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:32) 
                                                                                                    	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102) 
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46) 
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) 
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:938) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:226) 
                                                                                                    	at android.os.Looper.loop(Looper.java:313) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8663) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135) 
2023-09-22 21:09:13.154 29923-29923 LightWalletClient       com.nighthawkapps.wallet.android     W  Networking error: DEADLINE_EXCEEDED: deadline exceeded after 9.995976539s. [closed=[], open=[[remote_addr=mainnet.lightwalletd.com/140.238.134.157:9067]]]

**Comment by HonzaR** [comment]
Hi @Mandeepbhalothia, Thank you for the issue. From the log above, it seems like your device is experiencing some kind of network error. See the line:
 ```
 LightWalletClient com.nighthawkapps.wallet.android W Networking error: DEADLINE_EXCEEDED: deadline exceeded after 9.996491770s. [closed=[], open=[[remote_addr=mainnet.lightwalletd.com/140.238.134.157:9067]]]
 ```
 Which is the route cause of canceled flow. Please note that most of the log you've sent is just about proper SDK recovery after some external action happened, which could be any connection/storage/system optimizations/etc. problems.  The `AbortFlowException` is saying that the SDK wasn't able to download blocks in the stream way due to some of the mentioned problems. What could be more interesting is the part above the `AbortFlowException`, but we already know that it was connection trouble on your device's side.
