### ISSUE TITLE
App is crashing on Android 11

### ISSUE THREAD

**Issue by rafaelekol** [zcash/zcash-android-wallet-sdk#198]
**What is the bug?**
In Unstoppable Wallet, which is using you SDK, app is crashing on Android 11. One of our users has reported this [issue](https://github.com/horizontalsystems/unstoppable-wallet-android/issues/3013), and directed to [solution](https://github.com/square/okhttp/issues/5816) to increase OkHttp version.

**Crash log**
 ```
grpc-okhttp-0
    Process: io.horizontalsystems.bankwallet.dev, PID: 7840
    java.lang.AssertionError: Method getAlpnSelectedProtocol not supported for object SSL socket over Socket[address=zcash.horizontalsystems.xyz/167.99.236.5,port=9067,localPort=39814]
        at io.grpc.okhttp.internal.OptionalMethod.invoke(OptionalMethod.java:114)
        at io.grpc.okhttp.internal.OptionalMethod.invokeWithoutCheckedException(OptionalMethod.java:135)
        at io.grpc.okhttp.OkHttpProtocolNegotiator$AndroidNegotiator.getSelectedProtocol(OkHttpProtocolNegotiator.java:183)
        at io.grpc.okhttp.OkHttpProtocolNegotiator$AndroidNegotiator.negotiate(OkHttpProtocolNegotiator.java:145)
        at io.grpc.okhttp.OkHttpTlsUpgrader.upgrade(OkHttpTlsUpgrader.java:63)
        at io.grpc.okhttp.OkHttpClientTransport$4.run(OkHttpClientTransport.java:568)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
```

**Comment by gmale** [comment]
Sorry for delay. Just noticed this issue, due to the holiday break. It seems that the root issue is pretty straight-forward:
 the underlying library (OkHttp) was making calls to hidden methods through reflection and the use of `getAlpnSelectedProtocol` just needs to be replaced with ` javax.net.ssl.SSLSocket#getApplicationProtocol()` and that change was made and merged back in February.
 
However, [as noted here](https://github.com/zcash/zcash-android-wallet-sdk/blob/master/build.gradle#L15) this library has been stuck on an older version of the grpc library (1.25.0) due to compatibility issues that would cause breaking changes in multiple places (all consumers of the protobufs: iOS, Android and GoLang). Consequently, gRPC is [pulling in the older version of okhttp](https://github.com/zcash/zcash-android-wallet-sdk/blob/master/build.gradle#L241).

I'll dig into this and get a better idea of exactly how painful it is to clear this tech debt and I'll also investigate whether we can reduce the pain by switching over to [wire for gRPC](https://github.com/zcash/zcash-android-wallet-sdk/issues/178).

**Comment by gmale** [comment]
If the root issue was not fixed by these changes, we can re-open this issue.
