### ISSUE TITLE
Remove blocking IO calls from SDK

### ISSUE THREAD

**Issue by ccjernigan** [zcash/zcash-android-wallet-sdk#269]
The SDK has a number of blocking disk IO calls that occur during construction and setup.  Ideally, we'd move these off the main thread in a way that's transparent to clients of the SDK.

Blocking IO calls have a risk of triggering "application not responding" errors on Android.  These are especially common for lower-end devices, but can happen on any Android device that performs IO on the UI thread.

This will be a larger task that will potentially require public API changes (moving certain initializers to suspending functions), as well as a variety of internal changes to how the SDK works.

#268 is an initial issue that will help us identify blocking calls so that additional sub-issues can be created.

This is a running list of APIs found so far that are blocking.  Below are the stacktraces from StrictMode, making it easier to trace each individual violation.

- [x] SDKInitializer
    - [x] Calls to getDatabasePath
    - [x] Calls to Context.getCacheDir()
    - [x] Calls to initialize the SQLight database
- [x] SDKSynchronizer
    - [x] Listing transactions makes calls to SQLite database
- [x] DerivationTool
    - [x] Loading Rust backend

```
StrictMode policy violation; ~duration=25 ms: android.os.strictmode.DiskReadViolation
	at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1556)
	at libcore.io.BlockGuardOs.access(BlockGuardOs.java:69)
	at libcore.io.ForwardingOs.access(ForwardingOs.java:73)
	at android.app.ActivityThread$AndroidOs.access(ActivityThread.java:7246)
	at java.io.UnixFileSystem.checkAccess(UnixFileSystem.java:281)
	at java.io.File.exists(File.java:815)
	at android.app.ContextImpl.ensurePrivateDirExists(ContextImpl.java:645)
	at android.app.ContextImpl.ensurePrivateDirExists(ContextImpl.java:636)
	at android.app.ContextImpl.getDatabasesDir(ContextImpl.java:875)
	at android.app.ContextImpl.getDatabasePath(ContextImpl.java:854)
	at android.content.ContextWrapper.getDatabasePath(ContextWrapper.java:331)
	at cash.z.ecc.android.sdk.Initializer$Companion.aliasToPath(Initializer.kt:396)
	at cash.z.ecc.android.sdk.Initializer$Companion.dataDbPath$zcash_android_sdk_1_3_0_beta18_release(Initializer.kt:392)
	at cash.z.ecc.android.sdk.Initializer.initRustBackend(Initializer.kt:65)
	at cash.z.ecc.android.sdk.Initializer.<init>(Initializer.kt:50)
	at cash.z.ecc.android.sdk.Initializer.<init>(Initializer.kt:58)
	at cash.z.ecc.android.sdk.Initializer.<init>(Initializer.kt:58)
	at cash.z.ecc.android.sdk.demoapp.demos.getbalance.GetBalanceFragment.setup(GetBalanceFragment.kt:51)
	at cash.z.ecc.android.sdk.demoapp.demos.getbalance.GetBalanceFragment.onCreate(GetBalanceFragment.kt:36)
```

```
StrictMode policy violation; ~duration=25 ms: android.os.strictmode.DiskReadViolation
	at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1556)
	at libcore.io.BlockGuardOs.access(BlockGuardOs.java:69)
	at libcore.io.ForwardingOs.access(ForwardingOs.java:73)
	at android.app.ActivityThread$AndroidOs.access(ActivityThread.java:7246)
	at java.io.UnixFileSystem.checkAccess(UnixFileSystem.java:281)
	at java.io.File.exists(File.java:815)
	at android.app.ContextImpl.ensurePrivateDirExists(ContextImpl.java:645)
	at android.app.ContextImpl.ensurePrivateCacheDirExists(ContextImpl.java:641)
	at android.app.ContextImpl.getCacheDir(ContextImpl.java:734)
	at android.content.ContextWrapper.getCacheDir(ContextWrapper.java:273)
	at cash.z.ecc.android.sdk.Initializer.initRustBackend(Initializer.kt:66)
	at cash.z.ecc.android.sdk.Initializer.<init>(Initializer.kt:50)
	at cash.z.ecc.android.sdk.Initializer.<init>(Initializer.kt:58)
	at cash.z.ecc.android.sdk.Initializer.<init>(Initializer.kt:58)
	at cash.z.ecc.android.sdk.demoapp.demos.getbalance.GetBalanceFragment.setup(GetBalanceFragment.kt:51)
	at cash.z.ecc.android.sdk.demoapp.demos.getbalance.GetBalanceFragment.onCreate(GetBalanceFragment.kt:36)

```

```
StrictMode policy violation; ~duration=42 ms: android.os.strictmode.DiskReadViolation
	at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1556)
	at android.database.sqlite.SQLiteConnection.applyBlockGuardPolicy(SQLiteConnection.java:1138)
	at android.database.sqlite.SQLiteConnection.executeForLong(SQLiteConnection.java:688)
	at android.database.sqlite.SQLiteConnection.setAutoCheckpointInterval(SQLiteConnection.java:270)
	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:226)
	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:197)
	at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:505)
	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:206)
	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:198)
	at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:915)
	at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:895)
	at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:759)
	at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:748)
	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:374)
	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:317)
	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.getWritableSupportDatabase(FrameworkSQLiteOpenHelper.java:145)
	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper.getWritableDatabase(FrameworkSQLiteOpenHelper.java:106)
	at cash.z.ecc.android.sdk.transaction.PagedTransactionRepository.buildDatabase(PagedTransactionRepository.kt:179)
	at cash.z.ecc.android.sdk.transaction.PagedTransactionRepository.prepare(PagedTransactionRepository.kt:105)
	at cash.z.ecc.android.sdk.SdkSynchronizer.prepare(SdkSynchronizer.kt:251)
	at cash.z.ecc.android.sdk.SdkSynchronizer$onReady$2.invokeSuspend(SdkSynchronizer.kt:394)
```

```
StrictMode policy violation; ~duration=8 ms: android.os.strictmode.DiskReadViolation
	at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1556)
	at android.database.sqlite.SQLiteConnection.applyBlockGuardPolicy(SQLiteConnection.java:1138)
	at android.database.sqlite.SQLiteConnection.executeForLong(SQLiteConnection.java:688)
	at android.database.sqlite.SQLiteConnection.setAutoCheckpointInterval(SQLiteConnection.java:272)
	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:226)
	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:197)
	at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:505)
	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:206)
	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:198)
	at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:915)
	at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:895)
	at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:759)
	at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:748)
	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:374)
	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:317)
	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.getWritableSupportDatabase(FrameworkSQLiteOpenHelper.java:145)
	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper.getWritableDatabase(FrameworkSQLiteOpenHelper.java:106)
	at cash.z.ecc.android.sdk.transaction.PagedTransactionRepository.buildDatabase(PagedTransactionRepository.kt:179)
	at cash.z.ecc.android.sdk.transaction.PagedTransactionRepository.prepare(PagedTransactionRepository.kt:105)
	at cash.z.ecc.android.sdk.SdkSynchronizer.prepare(SdkSynchronizer.kt:251)
	at cash.z.ecc.android.sdk.SdkSynchronizer$onReady$2.invokeSuspend(SdkSynchronizer.kt:394)
```

```
StrictMode policy violation; ~duration=54 ms: android.os.strictmode.DiskReadViolation
	at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1556)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:247)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7255)
	at libcore.io.IoUtils.canOpenReadOnly(IoUtils.java:288)
	at dalvik.system.DexPathList$NativeLibraryElement.findNativeLibrary(DexPathList.java:889)
	at dalvik.system.DexPathList.findLibrary(DexPathList.java:600)
	at dalvik.system.BaseDexClassLoader.findLibrary(BaseDexClassLoader.java:270)
	at java.lang.Runtime.loadLibrary0(Runtime.java:1060)
	at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
	at java.lang.System.loadLibrary(System.java:1667)
	at cash.z.ecc.android.sdk.jni.RustBackend$Companion.loadRustLibrary(RustBackend.kt:258)
	at cash.z.ecc.android.sdk.jni.RustBackend$Companion.load(RustBackend.kt:235)
	at cash.z.ecc.android.sdk.tool.DerivationTool$Companion.withRustBackendLoaded(DerivationTool.kt:10
	at cash.z.ecc.android.sdk.tool.DerivationTool$Companion.deriveSpendingKeys(DerivationTool.kt:49)
```

**Comment by geffenz** [comment]
Merged! Closing.
