### ISSUE TITLE
UnsatisfiedLinkError in DerivationTool.deriveExtendedSpendingKeys

### ISSUE THREAD

**Issue by HonzaR** [zcash/zcash-android-wallet-sdk#723]
### Describe the issue
The app suffers with `UnsatisfiedLinkError: No implementation found for java.lang.String[]` , which has root in `DerivationTool.deriveExtendedSpendingKeys`. I can't duplicate it on a real device or emulator. The only suspicious thing I can see here is that the `deriveExtendedSpendingKeys` and `deriveUnifiedViewingKeysFromSeed` have different return types in Kotlin layer, but the same in Rust layer, but I don't know if that is the problem.

**Kotlin:**
```
        @JvmStatic
        private external fun deriveExtendedSpendingKeys(
            seed: ByteArray,
            numberOfAccounts: Int,
            networkId: Int
        ): Array<String>

        @JvmStatic
        private external fun deriveUnifiedViewingKeysFromSeed(
            seed: ByteArray,
            numberOfAccounts: Int,
            networkId: Int
        ): Array<Array<String>>
```
**Rust:**
```
pub unsafe extern "C" fn Java_cash_z_ecc_android_sdk_tool_DerivationTool_deriveExtendedSpendingKeys(
    env: JNIEnv<'_>,
    _: JClass<'_>,
    seed: jbyteArray,
    accounts: jint,
    network_id: jint,
) -> jobjectArray

pub unsafe extern "C" fn Java_cash_z_ecc_android_sdk_tool_DerivationTool_deriveUnifiedViewingKeysFromSeed(
    env: JNIEnv<'_>,
    _: JClass<'_>,
    seed: jbyteArray,
    accounts: jint,
    network_id: jint,
) -> jobjectArray
```
Can this be the problem? Here is a [link to the Firebase Test Lab report](https://console.firebase.google.com/u/4/project/android-sdk-14de8/testlab/histories/bh.64cb84454054609/matrices/9130390037439444048/executions/bs.4fe9f7c77430d97a?hl=en)

And here is a complete stacktrace:
```
java.lang.UnsatisfiedLinkError: No implementation found for java.lang.String[] cash.z.ecc.android.sdk.tool.DerivationTool.deriveExtendedSpendingKeys(byte[], int, int) (tried Java_cash_z_ecc_android_sdk_tool_DerivationTool_deriveExtendedSpendingKeys and Java_cash_z_ecc_android_sdk_tool_DerivationTool_deriveExtendedSpendingKeys___3BII)
     FATAL EXCEPTION: main
Process: cash.z.ecc.android.sdk.demoapp.mainnet, PID: 7790
java.lang.UnsatisfiedLinkError: No implementation found for java.lang.String[] cash.z.ecc.android.sdk.tool.DerivationTool.deriveExtendedSpendingKeys(byte[], int, int) (tried Java_cash_z_ecc_android_sdk_tool_DerivationTool_deriveExtendedSpendingKeys and Java_cash_z_ecc_android_sdk_tool_DerivationTool_deriveExtendedSpendingKeys___3BII)
	at cash.z.ecc.android.sdk.tool.DerivationTool.deriveExtendedSpendingKeys(Native Method)
	at cash.z.ecc.android.sdk.tool.DerivationTool.b(Unknown Source:0)
	at cash.z.ecc.android.sdk.tool.b.d(SourceFile:9)
	at cash.z.ecc.android.sdk.tool.DerivationTool$a.d(SourceFile:71)
	at cash.z.ecc.android.sdk.tool.DerivationTool$a$d.m(Unknown Source:12)
	at w4.a.o(Unknown Source:8)
	at k5.i0.run(Unknown Source:100)
	at androidx.lifecycle.e.a(SourceFile:45)
	at androidx.lifecycle.d.run(SourceFile:13)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at androidx.test.espresso.base.Interrogator.loopAndInterrogate(Interrogator.java:10)
	at androidx.test.espresso.base.UiControllerImpl.loopUntil(UiControllerImpl.java:7)
	at androidx.test.espresso.base.UiControllerImpl.loopUntil(UiControllerImpl.java:1)
	at androidx.test.espresso.base.UiControllerImpl.injectMotionEvent(UiControllerImpl.java:5)
	at androidx.test.espresso.action.MotionEvents.sendUp(MotionEvents.java:6)
	at androidx.test.espresso.action.MotionEvents.sendUp(MotionEvents.java:1)
	at androidx.test.espresso.action.Tap.sendSingleTap(Tap.java:5)
	at androidx.test.espresso.action.Tap.-$$Nest$smsendSingleTap(Unknown Source:0)
	at androidx.test.espresso.action.Tap$1.sendTap(Tap.java:1)
	at androidx.test.espresso.action.GeneralClickAction.perform(GeneralClickAction.java:4)
	at androidx.test.espresso.ViewInteraction$SingleExecutionViewAction.perform(ViewInteraction.java:2)
	at androidx.test.espresso.ViewInteraction.doPerform(ViewInteraction.java:21)
	at androidx.test.espresso.ViewInteraction.-$$Nest$mdoPerform(Unknown Source:0)
	at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:6)
	at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7898)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
	Suppressed: k5.g0: [m1{Cancelling}@ac0bc22, Dispatchers.Main.immediate]
```

### Expected behaviour
Our `test-robo-demo-app` CI job will go through the app without this failure.

### Any extra information that might be useful in the debugging process.
Might get fixed when we merge another change that is in progress to support unified spending keys - https://github.com/zcash/zcash-android-wallet-sdk/pull/717.

**Comment by ccjernigan** [comment]
With more recent changes to the SDK, the stack trace looks more like this

```
java.lang.UnsatisfiedLinkError: No implementation found for cash.z.ecc.android.sdk.model.UnifiedSpendingKey cash.z.ecc.android.sdk.tool.DerivationTool.deriveSpendingKey(byte[], int, int) (tried Java_cash_z_ecc_android_sdk_tool_DerivationTool_deriveSpendingKey and Java_cash_z_ecc_android_sdk_tool_DerivationTool_deriveSpendingKey___3BII)
     FATAL EXCEPTION: main
Process: cash.z.ecc.android.sdk.demoapp.mainnet, PID: 7847
java.lang.UnsatisfiedLinkError: No implementation found for cash.z.ecc.android.sdk.model.UnifiedSpendingKey cash.z.ecc.android.sdk.tool.DerivationTool.deriveSpendingKey(byte[], int, int) (tried Java_cash_z_ecc_android_sdk_tool_DerivationTool_deriveSpendingKey and Java_cash_z_ecc_android_sdk_tool_DerivationTool_deriveSpendingKey___3BII)
	at cash.z.ecc.android.sdk.tool.DerivationTool.deriveSpendingKey(Native Method)
	at cash.z.ecc.android.sdk.tool.DerivationTool.access$deriveSpendingKey(DerivationTool.kt:11)
	at cash.z.ecc.android.sdk.tool.DerivationTool$deriveUnifiedSpendingKey$2.invoke(DerivationTool.kt:67)
	at cash.z.ecc.android.sdk.tool.DerivationTool$deriveUnifiedSpendingKey$2.invoke(DerivationTool.kt:66)
	at cash.z.ecc.android.sdk.tool.DerivationTool.withRustBackendLoaded(DerivationTool.kt:110)
	at cash.z.ecc.android.sdk.tool.DerivationTool.access$withRustBackendLoaded(DerivationTool.kt:11)
	at cash.z.ecc.android.sdk.tool.DerivationTool$withRustBackendLoaded$1.invokeSuspend(Unknown Source:15)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at androidx.lifecycle.DispatchQueue.drainQueue(DispatchQueue.kt:75)
	at androidx.lifecycle.DispatchQueue.enqueue(DispatchQueue.kt:112)
	at androidx.lifecycle.DispatchQueue.access$enqueue(DispatchQueue.kt:31)
	at androidx.lifecycle.DispatchQueue$dispatchAndEnqueue$1$1.run(DispatchQueue.kt:100)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at androidx.test.espresso.base.Interrogator.loopAndInterrogate(Interrogator.java:10)
	at androidx.test.espresso.base.UiControllerImpl.loopUntil(UiControllerImpl.java:7)
	at androidx.test.espresso.base.UiControllerImpl.loopUntil(UiControllerImpl.java:1)
	at androidx.test.espresso.base.UiControllerImpl.injectMotionEvent(UiControllerImpl.java:5)
	at androidx.test.espresso.action.MotionEvents.sendUp(MotionEvents.java:6)
	at androidx.test.espresso.action.MotionEvents.sendUp(MotionEvents.java:1)
	at androidx.test.espresso.action.Tap.sendSingleTap(Tap.java:5)
	at androidx.test.espresso.action.Tap.-$$Nest$smsendSingleTap(Unknown Source:0)
	at androidx.test.espresso.action.Tap$1.sendTap(Tap.java:1)
	at androidx.test.espresso.action.GeneralClickAction.perform(GeneralClickAction.java:4)
	at androidx.test.espresso.ViewInteraction$SingleExecutionViewAction.perform(ViewInteraction.java:2)
	at androidx.test.espresso.ViewInteraction.doPerform(ViewInteraction.java:21)
	at androidx.test.espresso.ViewInteraction.-$$Nest$mdoPerform(Unknown Source:0)
	at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:6)
	at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7872)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@7447d7b, Dispatchers.Main.immediate]
```
